=== Meng-Heng/api.keyman.com/schemas/windows-update/14.0/windows-update.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$ref": "#/definitions/windows-update",

  "definitions": {
    "windows-update": {
      "type": "object",
      "required": [
        "msi",
        "setup",
        "bundle",
        "keyboards"
      ],
      "additionalProperties": true,
      "properties": {
        "msi": {
          "$ref": "#/definitions/file"
        },
        "setup": {
          "$ref": "#/definitions/file"
        },
        "bundle": {
          "$ref": "#/definitions/file"
        },
        "keyboards": {
          "$ref": "#/definitions/keyboards"
        }
      }
    },

    "file": {
      "type": "object",
      "required": [
        "name",
        "version",
        "date",
        "platform",
        "stability",
        "file",
        "md5",
        "type",
        "build",
        "size",
        "url"
      ],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "platform": {
          "type": "string"
        },
        "stability": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "md5": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "build": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "keyboards": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        ".+": {
          "$ref": "#/definitions/keyboard"
        }
      }
    },
    "keyboard": {
      "allOf": [
        {
          "$ref": "/keyboard_info.source/1.0.6/keyboard_info.source.json#/definitions/KeyboardInfo"
        },
        {
          "properties": {
            "url": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}

=== Meng-Heng/api.keyman.com/tests/fixtures/WindowsUpdateCheck.14.0.json
{
    "msi": {
        "name": "Keyman Desktop MSI installer",
        "version": "14.0.104.0",
        "date": "2020-07-01",
        "platform": "win",
        "stability": "alpha",
        "file": "keymandesktop.msi",
        "md5": "6EE552FA2522082489A547D3384637DC",
        "type": "exe",
        "build": "104",
        "size": 68677632,
        "url": "https://downloads.keyman.com/windows/alpha/14.0.104.0/keymandesktop.msi"
    },
    "setup": {
        "name": "Keyman Desktop setup bootstrap",
        "version": "14.0.104.0",
        "date": "2020-07-01",
        "platform": "win",
        "stability": "alpha",
        "file": "setup.exe",
        "md5": "24DF69CB03F91F4A424EBC76623B4956",
        "type": "exe",
        "build": "104",
        "size": 3153920,
        "url": "https://downloads.keyman.com/windows/alpha/14.0.104.0/setup.exe"
    },
    "bundle": {
        "name": "Keyman Desktop",
        "version": "14.0.104.0",
        "date": "2020-07-01",
        "platform": "win",
        "stability": "alpha",
        "file": "keymandesktop-14.0.104.0.exe",
        "md5": "F369D4FE5D3E47495E05EE3E2271DFFA",
        "type": "exe",
        "build": "104",
        "size": 69009424,
        "url": "https://downloads.keyman.com/windows/alpha/14.0.104.0/keymandesktop-14.0.104.0.exe"
    },
    "keyboards": {
        "khmer_angkor": {
            "id": "khmer_angkor",
            "name": "Khmer Angkor",
            "license": "mit",
            "related": {
                "khmer10": {
                    "deprecates": true
                }
            },
            "version": "1.0.6",
            "helpLink": "https://help.keyman.com/keyboard/khmer_angkor",
            "encodings": [
                "unicode"
            ],
            "languages": {
                "km": {
                    "font": {
                        "family": "Mondulkiri",
                        "source": [
                            "Mondulkiri-R.ttf"
                        ]
                    },
                    "displayName": "Central Khmer",
                    "languageName": "Central Khmer"
                }
            },
            "authorName": "Makara Sok",
            "jsFileSize": 63881,
            "jsFilename": "khmer_angkor.js",
            "sourcePath": "release/k/khmer_angkor",
            "authorEmail": "makara@keyman.com",
            "description": "<p>Khmer Unicode keyboard layout based on the NiDA keyboard layout. Automatically corrects many common keying errors.</p>",
            "packageFileSize": 2639344,
            "packageFilename": "khmer_angkor.kmp",
            "packageIncludes": [
                "visualKeyboard",
                "welcome",
                "fonts",
                "documentation"
            ],
            "platformSupport": {
                "ios": "full",
                "linux": "full",
                "macos": "full",
                "android": "full",
                "windows": "full",
                "mobileWeb": "full",
                "desktopWeb": "full"
            },
            "lastModifiedDate": "2020-06-30T23:59:32.089Z",
            "minKeymanVersion": "10.0",
            "url": "https://downloads.keyman.com/keyboards/khmer_angkor/1.0.6/khmer_angkor.kmp"
        }
    }
}
